# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-using-an-action-in-the-same-repository-as-the-workflow
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Env Prepare
description: 'prepare for building environment'
runs:
  using: "composite"
  steps:
    - name: Setup node
      # https://github.com/actions/setup-node
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        registry-url: https://registry.npmjs.org

    - name: Environment variables
      shell: bash
      run: |
        env

    - name: Install
      shell: bash
      run: |
        npm i -g npm@7
        npm ci

    - name: ESLint
      shell: bash
      run: |
        npm run lint

    - name: Unit test
      shell: bash
      run: |
        npm test
