# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Build for commit

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # https://github.com/chalk/supports-color/blob/main/index.js#L21
      # https://github.com/chalk/supports-color/blob/main/index.js#L54
      FORCE_COLOR: true

    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v3
        with:
          # Number of commits to fetch. 0 indicates all history.
          fetch-depth: 1

      - name: Prepare for building
        uses: ./.github/actions/prepare

      - name: Build package
        run: |
          npm run build

      - name: Build site
        run: |
          npm run build:site

      - name: Deploy site
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
